theme: jekyll-theme-minimal
title: 'Single Cell RNA-Seq Analysis'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Intro to the Workshop and Core
    url: base/welcome
  - title: Daily Tasks
    url: base/schedule
  #- title: What is Bioinformatics/Genomics?
  #  url: https://raw.githubusercontent.com/msettles/msettles.presentations/master/genomics/Genomics_a_perspective_Dec_2021.pdf
  #- title: Experimental Design and Cost Estimation
  #  url: https://raw.githubusercontent.com/msettles/msettles.presentations/master/singlecell/scRNAseq-expDesign_March_2022.pdf

  - heading: Support
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links

  - heading: Prerequisites, R
  - title: R
    url: https://ucdavis-bioinformatics-training.github.io/2022-April-Introduction-to-R-for-Bioinformatics/

  - heading: scRNAseq Analysis
  - title: Prepare scRNAseq Analysis
    url: data_analysis/scrna_analysis_prepare
  - title: scRNAseq Analysis - PART1
    url: data_analysis/scRNA_Workshop-PART1
  - title: scRNAseq Analysis - PART2
    url: data_analysis/scRNA_Workshop-PART2
  - title: scRNAseq Analysis - PART3
    url: data_analysis/scRNA_Workshop-PART3
  - title: scRNAseq Analysis - PART4
    url: data_analysis/scRNA_Workshop-PART4
  - title: scRNAseq Analysis - PART5
    url: data_analysis/scRNA_Workshop-PART5
  - title: scRNAseq Analysis - PART6
    url: data_analysis/scRNA_Workshop-PART6_with_quizzes
  - title: scRNAseq Analysis - PART7
    url: data_analysis/scRNA_Workshop-PART7
  # - title: Shiny App (extra)
  #   url: data_analysis/shiny_app_install
  # - title: Shiny App on AWS (extra)
  #   url: data_analysis/shiny_on_aws

  - heading: Prerequisites, CLI
  - title: CLI
    url: https://ucdavis-bioinformatics-training.github.io/2022-April-Introduction-to-the-Command-Line-for-Bioinformatics/

  - heading: Data Reduction
  - title: Files and Filetypes
    url: data_reduction/filetypes
  - title: Project setup
    url: data_reduction/project_setup
  - title: Generating Expression Matrix
    url: data_reduction/Expression_Matrix

  - heading: ETC
  - title: Closing thoughts
    url: base/closing
  - title: Discussions Page
    url: https://github.com/msettles/2022-Uganda-Single-Cell-RNA-Seq-Analysis/discussions
  - title: Github page
    url: https://github.com/msettles/2022-Uganda-Single-Cell-RNA-Seq-Analysis
